# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orchestrate or schedule a set of jobs
jobs:
  printhello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello world
  print_my_name:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo Esraa Ebrahim
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - printhello
      - print_my_name
          # requires:
          #   - printhello